
import type { Farmer, Market, Produce } from '@/lib/types';
import { Apple, Carrot, Leaf, Wheat } from 'lucide-react';

export const PRODUCE_TYPES = [
  { name: 'Apple', icon: Leaf },
  { name: 'Apricot', icon: Leaf },
  { name: 'Avocado', icon: Leaf },
  { name: 'Banana', icon: Leaf },
  { name: 'Blackberry', icon: Leaf },
  { name: 'Blueberry', icon: Leaf },
  { name: 'Cherry', icon: Leaf },
  { name: 'Coconut', icon: Leaf },
  { name: 'Cranberry', icon: Leaf },
  { name: 'Date', icon: Leaf },
  { name: 'Fig', icon: Leaf },
  { name: 'Grape', icon: Leaf },
  { name: 'Grapefruit', icon: Leaf },
  { name: 'Guava', icon: Leaf },
  { name: 'Kiwi', icon: Leaf },
  { name: 'Lemon', icon: Leaf },
  { name: 'Lime', icon: Leaf },
  { name: 'Lychee', icon: Leaf },
  { name: 'Mango', icon: Leaf },
  { name: 'Melon', icon: Leaf },
  { name: 'Nectarine', icon: Leaf },
  { name: 'Orange', icon: Leaf },
  { name: 'Papaya', icon: Leaf },
  { name: 'Passionfruit', icon: Leaf },
  { name: 'Peach', icon: Leaf },
  { name: 'Pear', icon: Leaf },
  { name: 'Persimmon', icon: Leaf },
  { name: 'Pineapple', icon: Leaf },
  { name: 'Plum', icon: Leaf },
  { name: 'Pomegranate', icon: Leaf },
  { name: 'Raspberry', icon: Leaf },
  { name: 'Strawberry', icon: Leaf },
  { name: 'Tangerine', icon: Leaf },
  { name: 'Watermelon', icon: Leaf },
  { name: 'Artichoke', icon: Leaf },
  { name: 'Arugula', icon: Leaf },
  { name: 'Asparagus', icon: Leaf },
  { name: 'Beet', icon: Leaf },
  { name: 'Bell Pepper', icon: Leaf },
  { name: 'Broccoli', icon: Leaf },
  { name: 'Brussels Sprout', icon: Leaf },
  { name: 'Cabbage', icon: Leaf },
  { name: 'Carrot', icon: Carrot },
  { name: 'Cauliflower', icon: Leaf },
  { name: 'Celery', icon: Leaf },
  { name: 'Chard', icon: Leaf },
  { name: 'Collard Greens', icon: Leaf },
  { name: 'Corn', icon: Leaf },
  { name: 'Cucumber', icon: Leaf },
  { name: 'Eggplant', icon: Leaf },
  { name: 'Fennel', icon: Leaf },
  { name: 'Garlic', icon: Leaf },
  { name: 'Ginger', icon: Leaf },
  { name: 'Green Bean', icon: Leaf },
  { name: 'Kale', icon: Leaf },
  { name: 'Leek', icon: Leaf },
  { name: 'Lettuce', icon: Leaf },
  { name: 'Mushroom', icon: Leaf },
  { name: 'Mustard Greens', icon: Leaf },
  { name: 'Okra', icon: Leaf },
  { name: 'Onion', icon: Leaf },
  { name: 'Parsnip', icon: Leaf },
  { name: 'Pea', icon: Leaf },
  { name: 'Potato', icon: Leaf },
  { name: 'Pumpkin', icon: Leaf },
  { name: 'Radish', icon: Leaf },
  { name: 'Rhubarb', icon: Leaf },
  { name: 'Rutabaga', icon: Leaf },
  { name: 'Scallion', icon: Leaf },
  { name: 'Shallot', icon: Leaf },
  { name: 'Spinach', icon: Leaf },
  { name: 'Squash', icon: Leaf },
  { name: 'Sweet Potato', icon: Leaf },
  { name: 'Tomato', icon: Leaf },
  { name: 'Turnip', icon: Leaf },
  { name: 'Zucchini', icon: Leaf },
  { name: 'Almond', icon: Leaf },
  { name: 'Cashew', icon: Leaf },
  { name: 'Chestnut', icon: Leaf },
  { name: 'Hazelnut', icon: Leaf },
  { name: 'Macadamia', icon: Leaf },
  { name: 'Peanut', icon: Leaf },
  { name: 'Pecan', icon: Leaf },
  { name: 'Pistachio', icon: Leaf },
  { name: 'Walnut', icon: Leaf },
  { name: 'Basil', icon: Leaf },
  { name: 'Chives', icon: Leaf },
  { name: 'Cilantro', icon: Leaf },
  { name: 'Dill', icon: Leaf },
  { name: 'Mint', icon: Leaf },
  { name: 'Oregano', icon: Leaf },
  { name: 'Parsley', icon: Leaf },
  { name: 'Rosemary', icon: Leaf },
  { name: 'Sage', icon: Leaf },
  { name: 'Thyme', icon: Leaf },
  { name: 'Wheat', icon: Wheat },
];

export const produce: Produce[] = [
  {
    id: 'p1',
    name: 'Organic Tomatoes',
    icon: Leaf,
    quantity: 50,
    price: 250,
    description: 'Fresh, sun-ripened organic tomatoes, perfect for salads and sauces.',
    variety: 'Roma',
    imageUrl: 'https://picsum.photos/400/300?random=10'
  },
  {
    id: 'p2',
    name: 'Crisp Lettuce',
    icon: Leaf,
    quantity: 30,
    price: 120,
    description: 'Crisp and fresh romaine lettuce, grown locally without pesticides.',
    variety: 'Romaine',
    imageUrl: 'https://picsum.photos/400/300?random=11'
  },
  {
    id: 'p3',
    name: 'Gala Apples',
    icon: Apple,
    quantity: 120,
    price: 300,
    description: 'Sweet and juicy Gala apples, ideal for snacking or baking.',
    variety: 'Gala',
    imageUrl: 'https://picsum.photos/400/300?random=12'
  },
  {
    id: 'p4',
    name: 'Sweet Carrots',
    icon: Carrot,
    quantity: 75,
    price: 150,
    description: 'Vibrant orange carrots, great for roasting, steaming, or eating raw.',
    variety: 'Nantes',
    imageUrl: 'https://picsum.photos/400/300?random=13'
  },
];

export const farmers: Farmer[] = [
  {
    id: 'f1',
    name: 'Alice Green',
    location: 'Valley Farm, CA',
    avatarUrl: 'https://picsum.photos/100/100?random=1',
    bio: 'A third-generation farmer passionate about sustainable agriculture and growing the freshest produce for the local community.',
    produce: [produce[0], produce[1]],
  },
  {
    id: 'f2',
    name: 'Bob White',
    location: 'Hillside Orchard, OR',
    avatarUrl: 'https://picsum.photos/100/100?random=2',
    bio: 'Specializing in heirloom apple varieties and organic farming practices for over 20 years.',
    produce: [produce[2]],
  },
  {
    id: 'f3',
    name: 'Charlie Brown',
    location: 'Sunrise Fields, TX',
    avatarUrl: 'https://picsum.photos/100/100?random=3',
    bio: 'We run a family-owned farm focusing on root vegetables and providing fresh, healthy food for everyone.',
    produce: [produce[3], produce[1]],
  },
  {
    id: 'f4',
    name: 'Diana Prince',
    location: 'Green Pastures, VT',
    avatarUrl: 'https://picsum.photos/100/100?random=4',
    bio: 'Committed to organic methods and biodiversity, our farm offers a wide range of seasonal vegetables.',
    produce: [produce[0], produce[1], produce[3]],
  },
];

export const markets: Market[] = [
  {
    id: 'm1',
    name: 'City Center Farmers Market',
    location: '123 Main St, Downtown',
    imageUrl: 'https://picsum.photos/600/400?random=5',
    contact: 'market@example.com',
    operatingHours: 'Saturdays, 8 AM - 2 PM',
  },
  {
    id: 'm2',
    name: 'Riverside Organic Market',
    location: '456 River Rd, Suburbia',
    imageUrl: 'https://picsum.photos/600/400?random=6',
    contact: 'riverside.market@example.com',
    operatingHours: 'Sundays, 9 AM - 1 PM',
  },
  {
    id: 'm3',
    name: 'Uptown Grocers',
    location: '789 High St, Uptown',
    imageUrl: 'https://picsum.photos/600/400?random=7',
    contact: 'contact@uptowngrocers.com',
    operatingHours: 'Mon-Fri, 9 AM - 8 PM',
  },
  {
    id: 'm4',
    name: 'Community Food Co-op',
    location: '101 Community Dr, West End',
    imageUrl: 'https://picsum.photos/600/400?random=8',
    contact: 'info@communitycoop.org',
    operatingHours: 'Daily, 10 AM - 7 PM',
  },
];
